version: "3"
services:
  api-database:
    image: mongo:4.4.0
    container_name: "api-database"
    ports:
      - 27017:27017
  api:
    image: api-java-mongo
    ports:
      - 9091:8080
    links:
      - api-database